<h3>Enter your mobile Number</h3>
<form class="form create account form-create-account" action="<?= $this->getUrl('custompayment/index/telephonepost') ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off" novalidate="novalidate">
<div class="field required">
    <label for="telephone" class="label"><span>Telephone</span></label>
    <div class="control">
        <input type="number" name="telephone" autocomplete="telephone" id="telephone" title="Telephone" class="input-text" data-validate="{required:true}" aria-required="true">
    </div>
</div>
    <button type="submit" class="action submit primary" title="Save Number"><span>Save</span></button>
</form>
